name: Get latest data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *" # Run at 4am UTC on the first of the month

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the uv project
        run: uv sync --locked --all-extras --dev

      - name: Get latest data
        run: uv run python main.py

      - uses: EndBug/add-and-commit@v9

  deploy:
    needs: run
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Pull latest changes
        run: git pull origin ${{ github.ref_name }}

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
