name: Get latest data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *" # Run at 4am UTC on the first of the month

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6

      - name: Install the uv project
        run: uv sync --locked --all-extras --dev

      - name: Get latest data
        run: uv run python main.py

      - name: Delete old markdown reports (keep last 6)
        run: |
          ls -1 reports/*.md 2>/dev/null | sort | head -n -6 | xargs -r rm

      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9
