name: Get latest data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *" # Run at 4am UTC on the first of the month

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the uv project
        run: uv sync --locked --all-extras --dev

      - name: Get latest data
        run: uv run python main.py

      - uses: EndBug/add-and-commit@v9
