name: Get latest data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 1 * *" # Run at 7am on the first of the month

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Get latest data
        run: python main.py
      - uses: EndBug/add-and-commit@v9
